# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('currentprice', models.DecimalField(decimal_places=4, default=1000.0, max_digits=11)),
            ],
        ),
    ]
