# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='description',
            new_name='describ',
        ),
    ]
