# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0002_auto_20160614_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('amazon', models.PositiveSmallIntegerField(default=0)),
                ('google', models.PositiveSmallIntegerField(default=0)),
                ('facebook', models.PositiveSmallIntegerField(default=0)),
                ('share1', models.PositiveSmallIntegerField(default=0)),
                ('share2', models.PositiveSmallIntegerField(default=0)),
                ('share3', models.PositiveSmallIntegerField(default=0)),
                ('share4', models.PositiveSmallIntegerField(default=0)),
                ('share5', models.PositiveSmallIntegerField(default=0)),
                ('share6', models.PositiveSmallIntegerField(default=0)),
                ('share7', models.PositiveSmallIntegerField(default=0)),
                ('share8', models.PositiveSmallIntegerField(default=0)),
                ('share9', models.PositiveSmallIntegerField(default=0)),
                ('share10', models.PositiveSmallIntegerField(default=0)),
                ('share11', models.PositiveSmallIntegerField(default=0)),
                ('share12', models.PositiveSmallIntegerField(default=0)),
                ('share13', models.PositiveSmallIntegerField(default=0)),
                ('share14', models.PositiveSmallIntegerField(default=0)),
                ('share15', models.PositiveSmallIntegerField(default=0)),
                ('share16', models.PositiveSmallIntegerField(default=0)),
                ('share17', models.PositiveSmallIntegerField(default=0)),
                ('share18', models.PositiveSmallIntegerField(default=0)),
                ('share19', models.PositiveSmallIntegerField(default=0)),
                ('share20', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
