# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0003_sharedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetail',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='sharedetail',
            name='id',
            field=models.PositiveSmallIntegerField(default=0, primary_key='True', serialize=False),
        ),
    ]
