# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0005_auto_20160614_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=-1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('time', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='amazon',
            new_name='Amazon',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='facebook',
            new_name='Facebook',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='google',
            new_name='Google',
        ),
        migrations.AddField(
            model_name='share',
            name='queries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharedetail',
            name='money_in_hand',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='share',
            name='currentprice',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=7),
        ),
    ]
