# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0006_auto_20160628_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetail',
            old_name='Amazon',
            new_name='ACME',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='Facebook',
            new_name='Ammunation_Pharma',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='Google',
            new_name='Bajrang_Cafe',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share1',
            new_name='Bakers_Street_Findings',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share10',
            new_name='Buzzinga_Entertainment',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share11',
            new_name='Daily_Planet',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share12',
            new_name='Evil_Inc',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share13',
            new_name='Gringotts_Bank',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share14',
            new_name='Hammer_Tech',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share15',
            new_name='Illuminati_Consolidations',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share16',
            new_name='LexCorp',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share17',
            new_name='Monsters_Inc',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share18',
            new_name='Olivanders_Wand',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share19',
            new_name='Oscorp_RnD',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share2',
            new_name='Palmer_Tech',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share20',
            new_name='Pearson_Hardman',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share3',
            new_name='SHIELD',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share4',
            new_name='STAR_Labs',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share5',
            new_name='Skynet',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share6',
            new_name='Strak_Industries',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share7',
            new_name='Umbrella_Corp',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share8',
            new_name='Walter_White_Inc',
        ),
        migrations.RenameField(
            model_name='sharedetail',
            old_name='share9',
            new_name='Wayne_Enterprises',
        ),
        migrations.AddField(
            model_name='sharedetail',
            name='Xaviers_School',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
