# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0007_auto_20160929_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedetail',
            old_name='Strak_Industries',
            new_name='Stark_Industries',
        ),
    ]
