# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0010_auto_20161001_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedetail',
            name='money_in_hand',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=20),
        ),
    ]
