# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0011_auto_20161001_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='queries_total',
            field=models.IntegerField(default=0),
        ),
    ]
