# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Share_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
    ]
