# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareName', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='share_data',
            name='describ',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
