# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160628_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('describ', models.CharField(default='ecommerce', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('describ', models.CharField(default='ecommerce', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('describ', models.CharField(default='ecommerce', max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Share_Data',
        ),
    ]
