# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160628_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_asd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='user_nitrr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('y', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='amazon',
            name='describ',
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='describ',
        ),
        migrations.RemoveField(
            model_name='google',
            name='describ',
        ),
    ]
