# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_user_asd2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_asd2',
        ),
    ]
