# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_delete_user_asd2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='x',
            field=models.DateTimeField(),
        ),
    ]
