# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20160630_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon',
            name='y',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
